# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_multicamera_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_show = QtWidgets.QLabel(self.centralwidget)
        self.label_show.setGeometry(QtCore.QRect(0, 0, 1920, 720))
        self.label_show.setObjectName("label_show")
        self.pushButton_takephotos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_takephotos.setGeometry(QtCore.QRect(330, 750, 101, 41))
        self.pushButton_takephotos.setObjectName("pushButton_takephotos")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(140, 750, 151, 41))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 760, 61, 21))
        self.label.setObjectName("label")
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(470, 750, 101, 41))
        self.pushButton_save.setObjectName("pushButton_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "面部信息采集"))
        self.label_show.setText(_translate("MainWindow", "Depth"))
        self.pushButton_takephotos.setText(_translate("MainWindow", "拍摄"))
        self.label.setText(_translate("MainWindow", "ID:"))
        self.pushButton_save.setText(_translate("MainWindow", "保存"))
